[package]
name = "conjecture-rust"
version = "2.0.0"
edition = "2021"
description = "Modern Rust port of Python Hypothesis's conjecture engine with perfect parity"
license = "MPL-2.0"
authors = ["Hypothesis Development Team"]
homepage = "https://hypothesis.works/"
repository = "https://github.com/HypothesisWorks/hypothesis"
keywords = ["testing", "property-based", "hypothesis", "conjecture", "fuzzing"]
categories = ["development-tools::testing"]

[lib]
name = "conjecture"

[dependencies]
# Pure Rust crypto to avoid OpenSSL dependencies (key insight from swift-hypothesis)
sha1 = "0.10"
sha2 = "0.10"
# Other core dependencies
rand = "0.8"
rand_chacha = "0.3"
byteorder = "1.4"
lazy_static = "1.4"
once_cell = "1.19"

[dev-dependencies]
# For property-based testing of our implementation
proptest = "1.0"
# For benchmarking
criterion = "0.5"
# For Python FFI verification
pyo3 = { version = "0.20", features = ["auto-initialize"] }

# Benchmarks will be added later
# [[bench]]
# name = "choice_performance"
# harness = false